name: Docker Image CI

on:
  push:
    branches: [ "v6" ]
  pull_request:
    branches: [ "v6" ]

jobs:

  build-brok-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Brok
      run: docker build . --file Dockerfile --tag brok:$(date +%s) brok:latest
