name: Docker Image CI

on:
  push:
    branches: [ "v6" ]
  pull_request:
    branches: [ "v6" ]

jobs:

  build-hardhat-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Hardhat
      run: docker build --target hardhat . --file Dockerfile --tag brok-hardhat:$(date +%s)
  
  build-graph-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for TheGraph
      run: docker build --target graph . --file Dockerfile --tag brok-thegraph:$(date +%s)
